import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Scandia = localFont({
  src: [
    {
      path: "./assets/fonts/Scandia-Light.woff2",
      weight: "400",
      style: "light",
    },
    {
      path: "./assets/fonts/Scandia-Regular.woff2",
      weight: "400",
      style: "regular",
    },
    {
      path: "./assets/fonts/Scandia-Medium.woff2",
      weight: "500",
      style: "medium",
    },
    {
      path: "./assets/fonts/Scandia-Bold.woff2",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Coding Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Scandia.className} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
